---
chords:
  Intro: |
    <C>---
    <G>---
    <F>---
    <F>---

  Verse: |-
    <C>---
    <G>---
    <F>---
    <F>---

    <C>---
    <G>---
    <F>---
    <F>---

    <C>---
    <G>---
    <F>---
    <F>---

  Chorus: |-
    <G>---
    <D>---
    <F>---
    <C>---

    <G>---
    <D>---
    <Dm>---
    <F>---

  Interlude: |
    <C>---
    <G>---
    <F>---
    <F>---

  Bridge: |-
    <C>---
    <G>---
    <F>---
    <F>---

    <C>---
    <G>---
    <Bb>---
    <F>---

  Chorus 3: |-
    <G>---
    <D>---
    <F>---
    <C>---

    <G>---
    <D>---
    <F>---
    <C>---

    <G>---
    <D>---
    <Dm>---
    <F>---

  Outro: |-
    <C>---
    <G>---
    <F>---
    <F>---

    <C>---
    <G>---
    <F>---
    <F>---

    <C>---
    <G>---
    <Bb>---
    <F>---

lyrics:
- Intro: |
    ....
    ....
    ....
    ....


- Verse: |-
    Now that she's back in the atmosphere
    With drops of Jupiter in her hair
    ....
    ....

    She acts like summer and walks like rain
    Reminds me that there's a time to change
    ....
    ....

    Since the return from her stay on the moon
    She listens like spring and she talks like June
    ....
    ....

- Chorus: |-
    But tell me, did you sail across the sun?
    Did you make it to the Milky Way
    to see the lights all faded
    And that heaven is overrated?

    Tell me, did you fall for a shooting star
    One without a permanent scar
    And did you miss me while you were
    looking for yourself out there

- Interlude: |
    ....
    ....
    ....
    ....

- Verse: |-
    Now that she's back from that soul vacation
    Tracing her way through the constellation
    ....
    ....

    She checks out Mozart while she does taebo
    Reminds me that there's a room to grow
    ....
    ....

    Now that she's back in the atmosphere
    I'm afraid that she might think of me as
    plain old Jane told a story 'bout a man
    who was too afraid to fly so he never did land

- Chorus: |-
    But tell me, did the wind sweep you off your feet?
    Did you finally get the chance
    to dance along the light of day
    And head back to the Milky Way?

    And tell me, did Venus blow your mind?
    Was it everything you wanted to find?
    And did you miss me while you were
    looking for yourself out there?

- Interlude: |
    ....
    ....
    ....
    ....

- Bridge: |-
    Can you imagine no love, pride, deepfried chicken?
    Your best friend always
    sticking up for you
    even when I know you're wrong

    Can you imagine no first dance, freeze dried romance,
    fivehour phone conversation?
    The best soy latte that you ever had
    and me

- Chorus 3: |-
    But tell me, did the wind sweep you off your feet?
    Did you finally get the chance
    to dance along the light of day
    And head back to the Milky Way?

    And tell me, did you sail across the sun?
    Did you make it to the Milky Way
    to see the lights all faded
    And that heaven is overrated?

    Tell me, did you fall for a shooting star,
    One without a permanent scar?
    And did you miss me while you were
    looking for yourself?

- Outro: |-
    Na na na na na na
    Na na na na na na
    And did you finally get the chance
    to dance along the light of day?

    Na na na na na na
    Na na na na na na
    And did you fall for a shooting star,
    fall for a shooting star?

    Na na na na na na
    Na na na na na na
    And now you're lonely looking for yourself
    out there.
