details: |
  Key: G
  My preferred key: Bb

chords:
  Verse: |
    <G>- <C>-
    <Am>- <D>-
    <G>- <C>-
    <Am>- <D>-

  Pre-Chorus 1: |
    <G>- <C>-
    <Am>- <D>-
    <G>- <C>-
    <Am>- <D>-

  Pre-Chorus 2: |
    <G>- <C>-
    <Am>- <D>-

  Chorus 1: |
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-

  Solo: |
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-

    <G>- <C>- <Am>- <D>-
    <G>- <C>- <Am>- <D>-

  Pre-Chorus 3: |
    <G>- <C>-
    <Am>- <D>-
    <G>- <C>-
    <D>---

  Chorus 2: |
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-

  Outro: |
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-
    <Em>--- <C>- <D>-

lyrics:
  - Verse: |
      She doesn't own a dress, 
      her hair is always a mess
      If you catch her stealin' she won't confess
      She's beautiful

  - Verse: |
      Smokes a pack a day, 
      no wait, that's me, but anyway
      She doesn't care a thing about that, hey
      She thinks I'm beautiful

  - Pre-Chorus 1: |
      Meet Virginia
      .. ..
      .. ..
      .. ..

  - Verse: |
      She never compromises,
      loves babies and surprises
      Wears high heels when she exercises
      Ain't that beautiful

  - Pre-Chorus 2: |
      Meet Virginia
      .. ..

  - Chorus 1: |
      Well she wants to be the Queen
      Then she thinks about her scene
      Pulls her hair back as she screams
      "I don't really wanna be the Queen"

  - Verse: |
      Her Daddy wrestles alligators
      Mama works on carburetors
      And brother is a fine mediator
      For the President

  - Verse: |
      And here she is again on the phone
      Just like me hates to be alone
      We just like to sit at home
      And rip on the President

  - Pre-Chorus 2: |
      Meet Virginia
      .. ..

  - Chorus 1: |
      Well she wants to live her life
      Then she thinks about her life
      Pulls her hair back as she screams
      "I don't really wanna live this life"

  - Solo: |
      No mama
      .... .. ..
      .... .. ..
      .... .. ..

      .. .. .. ..
      .. .. .. ..

  - Verse: |
      She only drinks coffee at midnight
      When the moment is not right
      Her timing is quite
      Unusual

  - Verse: |
      You see her confidence is tragic
      But her intuition magic
      And the shape of her body?
      Unusual

  - Pre-Chorus 3: |
      Meet Virginia
      I can't wait to
      Meet Virginia
      Yeah yeah hey hey hey

  - Chorus 2: |
      Well she wants to be the queen
      And she thinks about her scene
      Well she wants to live her life
      Then she thinks about her life
      Pulls her hair back as she screams
      "I don't really wanna be the queen"

  - Outro: |
      I, I don't really wanna be the queen
      I, I don't really wanna be the queen
      I, I don't really wanna live this

